# Site settings
baseURL = "/"
languageCode = "en-US"
title = "Modern Baby Online"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2018 Modern Baby Online"

[params]

  # Metadata for search engines and social sharing
  author = "Modern Baby Online"
  description = "Modern Baby Online provides a donor management system for Baby Go Round"
  shareImage = "images/social.jpg"
  twitterHandle = "modernbabyonline"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "/images/modernbabyonline.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "/videos/cleaning.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Login"
        url = "https://app.modernbaby.online"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
